### ISSUE TITLE
Would a license under GPLv2+ be acceptable?

### ISSUE THREAD

**Issue by dereckson** [beardhatcode/python3-woof#1]
The woof original code is licensed under GPLv2+, would you consider to adopt that license too, so people can choose between GPLv2 and GPLv3?

I'm especially interested by your tests suite: I'm the previous woof FreeBSD port maintainer, a port dropped by lack of Python 3 support, and I'd like to incorporate your tests suite it into wurf, a project forking woof to actively maintain it under recent versions of Python.

It would be very nice if we could use it under GPLv2+.

**Comment by beardhatcode** [comment]
I see the orig woof developer also has a py3 implementation now that is under GPLv2 or later:

https://github.com/simon-budig/woof/blob/master/woof
